**Start with ndarray**

**How to create Rank i Numpy array**

In [4]:
import numpy as np

an_array = np.array([3,33,33])
print(type(an_array))
print(an_array.shape)
print(an_array[0], an_array[1], an_array[0])
an_array[0]= 688
print(an_array)

<class 'numpy.ndarray'>
(3,)
3 33 3
[688  33  33]


In [16]:
another= np.array([[12,13,15], [21,22,23]])
print(another)
print('Shape is 2 rows and three columns: ', another.shape)
print("Accesing element [0,0] , [0,1], [1,0] of the ndarray: ", another[0,0 0,1 1,0])

SyntaxError: invalid syntax (<ipython-input-16-c92bdcad8553>, line 4)

In [19]:
ex2 = np.zeros((2,2))
print(ex2)

[[0. 0.]
 [0. 0.]]


In [24]:
ex1 = np.full((3,3), 9.0) 
print(ex1)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [27]:
ex3 = np.eye(2,2) 
print(ex3)

[[1. 0.]
 [0. 1.]]


In [30]:
ex4 = np.ones((1,2)) 
print(ex4)

[[1. 1.]]


In [31]:
ex1 = np.full((3,3), 9.0) 
print(ex1.shape)

(3, 3)


In [69]:
import numpy as np

an_array = np.array([[32,31,33,56], [12,13,24,78], [11,34,44,70]] )
print(an_array)



[[32 31 33 56]
 [12 13 24 78]
 [11 34 44 70]]


In [70]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[31 33]
 [13 24]]


In [71]:
print("before:", an_array[0,1])


a_slice[0,0] = 2000
print("after:", an_array[0,1])

before: 31
after: 2000


In [82]:
row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

[12 13 24 78] (4,)


In [81]:
row_rank2 = an_array[1,2:, :]
print(row_rank2, row_rank2.shape)

IndexError: too many indices for array

In [86]:
print()
col_rank1 = an_array[:,1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, row_rank1.shape)
print()
print(col_rank2, row_rank2.shape)


[2000   13   34] (4,)

[[2000]
 [  13]
 [  34]] (2,)


In [88]:
import numpy as np

an_array = np.array([[32,31,33], [12,13,24], [11,34,44], [51,56,55]])
print("Orginal Array")
print(an_array)

Orginal Array
[[32 31 33]
 [12 13 24]
 [11 34 44]
 [51 56 55]]


In [90]:
col_indices =np.array([0,1,2,0])
print("\nCol indices picked:", col_indices)

row_indices = np.arange(4)
print("\nRow indices picked:", row_indices)


Col indices picked: [0 1 2 0]

Row indices picked: [0 1 2 3]


In [91]:
for row,col in zip(row_indices,col_indices):
    print(row,", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [93]:
print(an_array[row_indices,col_indices])

[32 13 44 51]


In [95]:
an_array[row_indices,col_indices] += 1000

print("\n changed array:" )
print(an_array)


 changed array:
[[2032   31   33]
 [  12 2013   24]
 [  11   34 2044]
 [2051   56   55]]


In [97]:
an_array = np.array([[32,31], [12,13], [11,34], [51,56]])
print(an_array)
filter = (an_array>15)
filter

[[32 31]
 [12 13]
 [11 34]
 [51 56]]


array([[ True,  True],
       [False, False],
       [False,  True],
       [ True,  True]])

In [99]:
print(an_array[filter])

[32 31 34 51 56]


In [101]:
an_array[an_array>15]

array([32, 31, 34, 51, 56])

In [103]:
an_array[(an_array>16) & (an_array<50)]

array([32, 31, 34])

In [105]:
an_array[an_array%2==0] +=100
print(an_array)

[[232  31]
 [212  13]
 [ 11 234]
 [ 51 256]]


In [110]:
exp_1 = np.array([12,23,21])
print(exp_1.dtype)

int64


In [111]:
exp_1 = np.array([12,23.3,21])
print(exp_1.dtype)

float64


In [114]:
exp_1 = np.array([12,23.0,21], dtype=np.int64)
print(exp_1.dtype)

int64


In [115]:
exp_1 = np.array([12,23.0,21], dtype=np.float64)
print(exp_1.dtype)

float64


In [116]:
exp_1 = np.array([12,23.0,21], dtype=np.float64)
print(exp_1)

[12. 23. 21.]


**Statistical Method, sorting and set oparetion**

In [124]:
arr =10 * np.random.randn(2,5)
print(arr)

[[ -4.26370947   2.04378678   0.24009827  13.53209887  17.61135775]
 [ -6.53756025 -18.36629792 -15.49272314   5.83941004 -15.5362619 ]]


In [125]:
print(arr.mean())

-2.0929800979631734


In [126]:
print(arr.mean(axis=0))

[-5.40063486 -8.16125557 -7.62631243  9.68575445  1.03754792]


In [127]:
print(arr.mean(axis=1))

[  5.83272644 -10.01868664]


-20.929800979631736


In [130]:
print(arr.max())

17.611357749925737


In [133]:
print(np.median(arr, axis=1))

[  2.04378678 -15.49272314]


**Sorting**

In [135]:
#create a 10 elements array of randoms
unsorted = np.random.randn(10)
print(unsorted)

[-0.18161943  0.43885124 -0.21783931 -1.36825117 -1.02270137 -1.57317299
  0.44344538  1.16290849 -1.32162038  2.27255528]


In [136]:
#create copy and sort
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.57317299 -1.36825117 -1.32162038 -1.02270137 -0.21783931 -0.18161943
  0.43885124  0.44344538  1.16290849  2.27255528]

[-0.18161943  0.43885124 -0.21783931 -1.36825117 -1.02270137 -1.57317299
  0.44344538  1.16290849 -1.32162038  2.27255528]


In [137]:
unsorted.sort()
print(unsorted)

[-1.57317299 -1.36825117 -1.32162038 -1.02270137 -0.21783931 -0.18161943
  0.43885124  0.44344538  1.16290849  2.27255528]


In [141]:
#Find unique elements of array

array = np.array([1,4,3,2,3,4,1,3,4])
print(np.unique(array))

[1 2 3 4]


In [143]:
# Set oparetion with nparry data type

s1 = np.array (['ali', 'ratul', 'rafi','sohel'])
s2 = np.array (['tamim', 'talha', 'sohel','ratul'])
print(s1,s2)

['ali' 'ratul' 'rafi' 'sohel'] ['tamim' 'talha' 'sohel' 'ratul']


In [144]:
print(np.intersect1d(s1,s2))

['ratul' 'sohel']


In [147]:
#s1 elements which are not in s2
print(np.setdiff1d(s1,s2))

['ali' 'rafi']


In [146]:
print(np.union1d(s1,s2))

['ali' 'rafi' 'ratul' 'sohel' 'talha' 'tamim']


In [148]:
#which elements of s1 also in s2
print(np.in1d(s1,s2))

[False  True False  True]


In [165]:
#broadcasting 
from numpy import *

start = zeros([4,3]) 
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [155]:
#create a rank 1 ndarry with three values
add_rows = [1,0,2]
print(add_rows)

[1, 0, 2]


In [156]:
y = start+add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [167]:
add_cols =[[0,1,2]]

print(add_cols)

[[0, 1, 2]]


In [168]:
y = start + add_cols
print(y)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [169]:
add_scalar = [1]
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [172]:
arr_1 = [[1,3,2,4], [3,5,6,7], [11,12,13,14]]
print(arr_1)

[[1, 3, 2, 4], [3, 5, 6, 7], [11, 12, 13, 14]]


**Speed Test: ndarray vs lists**

In [174]:
from numpy import arange
from timeit import Timer 

size = 1000000
timeits =1000

In [175]:
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [184]:
#timer expect operation as a paramiter 
# here pass nd_array.sum()

timer_numpy = Timer(" nd_array.sum()", "from__main__import nd_array")
print(" Time taken by the ndarray: %f seconds" % (timer_numpy.timeit(timeits)/timeits))

SyntaxError: invalid syntax (<timeit-src>, line 1)

In [182]:
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [185]:
timer_numpy = Timer("sum(a_list)", "from__main__import a_list")
print(" Time taken by the ndarray: %f seconds" % (a_list.timeit(timeits)/timeits))

SyntaxError: invalid syntax (<timeit-src>, line 1)